version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    volumes:
      - ./:/app
    command: npm test
    image: qedtechdocker/devops-for-programmers-project-lvl1