version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    volumes:
      - ./:/app
    command: npm test
    image: qedtechdocker/devops-for-programmers-project-lvl1
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_HOST: ${DATABASE_HOST}